### ISSUE TITLE
Is there a way of knowing which atoms come from which star?

### ISSUE THREAD

**Issue by errhernandez** [LaurentRDC/crystals#12]
Hi! This is a question, not an issue.

When constructing a Crystal instance from a cif file, is there a simple way of knowing which atoms in the Crystal result from the same Wyckoff position? In other words, are the atoms in the Crystal object ordered in some way by Wyckoff position in the space group? 

It would be useful to be able to relate Atom instances to the Wyckoff position from which they result, because when doing analysis one need only consider one representative per Wyckoff star. 

This might be a trivial question from someone not so familiar with crystallography ;-)

**Comment by LaurentRDC** [comment]
This is a good question.

The short answer is that no, the `Atom` objects don't contain Wyckoff position information. This is because not all CIFs / other formats carry this information.

There might be ways to recover the information however. Internally, `crystals` uses the library `spglib` to calculate symmetry-related quantities. For example you can resize the crystal unit cell to the primitive cell using `Crystal.primitive()`. If you peruse the [`spglib` documentation](https://spglib.github.io/spglib/), you might find a routine to help you. 

A quick search of "spglib wyckoff" brought me to [this issue](https://github.com/spglib/spglib/issues/100). Looks like this is what you want no? I'm happy to integrate it into `crystals`

**Comment by errhernandez** [comment]
Well, that would be great, if it is not too complicated; in fact, I think it would be sufficient to have an index array as part of the Crystal class and dimension equal to the number of atoms, identifying each atom to a particular orbit. Personally, this would be useful for me, but maybe for others too, but up to you if this should be integrated into crystals. Thanks, as always, for your helpful replies and willingness to help.

**Comment by LaurentRDC** [comment]
To be more specific, we could turn the following into a new method:

```python
>>> from spglib import get_symmetry_dataset
>>> from crystals import Crystal
>>> 
>>> graphite = Crystal.from_database('C')
>>> # Using an internal method here (_spglib_cell) which is not documented
>>> sym = get_symmetry_dataset(graphite._spglib_cell()) 
>>> 
>>> for atm, wyckoff_position in zip(graphite, sym['wyckoffs'], sym['crystallographic_orbits']):
...     print(repr(atm), ": Wyckoff letter=", wyckoff_position, " orbit=", orbit)
... 
< Atom C  @ (0.00, 0.00, 0.75) > : Wyckoff letter= b  orbit= 0
< Atom C  @ (0.33, 0.67, 0.25) > : Wyckoff letter= c  orbit= 1
< Atom C  @ (0.00, 0.00, 0.25) > : Wyckoff letter= b  orbit= 0
< Atom C  @ (0.67, 0.33, 0.75) > : Wyckoff letter= c  orbit= 1
```

In practice this won't always work right now because iterating over atoms has an undefined iteration order, but I could create a method which ensures the results are always correct

**Comment by LaurentRDC** [comment]
We could also do orbits as well, yes. All of this is easy to implement (thanks to `spglib`), so it's only a matter of describing exactly what you want. Having an example of expected output is even better, so we can add a few test cases

**Comment by errhernandez** [comment]
Hello again. Something like your example for graphite above would work beautifully for me. In practice I only need to identify a representative atom out of each group of symmetrically equivalent ones in the unit cell.

**Comment by LaurentRDC** [comment]
Since you want to keep 1 atom per symmetry site, I've opted to implement a 'group-by' operation instead. It currently looks like this:

```python
from crystals import Crystal
graphite = Crystal.from_database("C")

groups = graphite.groupby('crystallographic_orbits')
for orbit, group in groups.items():
    print("Orbit ", orbit, ": ", group)
```
with output:

```
Orbit 0 :  [< Atom C  @ (0.00, 0.00, 0.25) >, < Atom C  @ (0.00, 0.00, 0.75) >]
Orbit 2 :  [< Atom C  @ (0.33, 0.67, 0.25) >, < Atom C  @ (0.67, 0.33, 0.75) >]
```

You could substitute `"crystallographic_orbits"` by other site symmetries supported by spglib, e.g.  `"wyckoffs"`. I think this could be useful for many people.

If you like this, I''ll write some tests and add some documentation and create a new release tonight

**Comment by errhernandez** [comment]
This looks great, as far as I am concerned. I am sorry if I use the terminology a little bit loosely; I understood that an orbit or star is the group of atoms that results from a specific Wyckoff position after applying the space-group symmetry operations, but maybe this is not quite correct. Anyway, the solution you suggest would work for me. No hurry, though, I will not need it tonight ;-)

**Comment by LaurentRDC** [comment]
Great, I'm glad you like it.

I've never used the terms 'orbit' or 'star' really. I'm only basing my words on the spglib documentation for these terms, e.g. https://spglib.github.io/spglib/dataset.html#crystallographic-orbits. So I may also be bending the meaning of the terms as well.

I will ping back when the change has been release. Good suggestion!

**Comment by LaurentRDC** [comment]
[Release 1.6.0](https://pypi.org/project/crystals/1.6.0/) contains this change. Take a look [here](https://crystals.readthedocs.io/en/master/guides/crystals.html#grouping-atoms-by-site-symmetry) for a short example of how to use `Crystal.groupby`.

Don't hesitate to open other issues for questions and other suggestions
